global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using System.Windows;
global using CommunityToolkit.Mvvm.Input;
global using MonitoringBIMModel.ViewModels;
global using CommunityToolkit.Mvvm.ComponentModel;
global using Npgsql;
global using System.Collections.ObjectModel;
global using MonitoringBIMModel.Views;
global using MonitoringBIMModel.Models;
global using MonitoringBIMModel.Services;
global using DataObject = MonitoringBIMModel.Models.DataObject;
global using System.Windows.Controls;
global using Action = MonitoringBIMModel.Components.Action;
global using MonitoringBIMModel.Abstractions;
global using System.Reflection;
global using MonitoringBIMModel.Components;
global using System.ComponentModel;

